fix sync_secrets not fetching item

diff --git a/bin/sync_secrets b/bin/sync_secrets
--- a/bin/sync_secrets
+++ b/bin/sync_secrets
@@ -46,12 +46,19 @@ bitwarden() {
   if [[ "$op" == "pull" ]]; then
     echo "Pulling $secret_name from bitwarden"
 
-    local note=`bw get notes $secret_name`
+    # Search for item in the specific folder to avoid duplicate name issues (select first match)
+    local item=`bw list items --folderid "$folder_id" 2>/dev/null | jq -r "[.[] | select(.name==\"$secret_name\")] | first"`
+    local id=`echo $item | jq -r ".id"`
+    
+    if [[ "$id" == "" ]] || [[ "$id" == "null" ]]; then
+      echo "Secret '$secret_name' not found in folder '$folder'"
+      exit 1
+    fi
+
+    local note=`bw get notes $id`
 
     if [[ "${#note}" -eq 0 ]]; then
       echo "Note empty pulling attachment"
-      local item=`bw get item $secret_name 2>/dev/null`
-      local id=`echo $item | jq -r ".id"`
       # NOTE: output will always be the name of the attachment 
       bw get attachment $file_name --itemid $id
       exit 0
@@ -72,11 +79,11 @@ bitwarden() {
     local file_data=`jq -R -s '.' < $file_name`
     local data_length=${#file_data}
 
-    local item=`bw get item $secret_name 2>/dev/null`
-    local item_folder_id=`echo $item | jq -r ".folderId"`
+    # Search for item in the specific folder to avoid duplicate name issues (select first match)
+    local item=`bw list items --folderid "$folder_id" 2>/dev/null | jq -r "[.[] | select(.name==\"$secret_name\")] | first"`
     local id=`echo $item | jq -r ".id"`
     
-    if [[ "$id" == "" ]]; then
+    if [[ "$id" == "" ]] || [[ "$id" == "null" ]]; then
       echo "Secret '$secret_name' not found"
 
       if [[ "$data_length" -gt 7500 ]]; then 
@@ -93,13 +100,6 @@ bitwarden() {
       echo "Creating '$secret_name' in folder '$folder' as note"
       bw get template item | jq ".type=2" | jq ".collectionIds=[]" | jq ".name=\"$secret_name\"" | jq ".folderId=\"$folder_id\"" | jq ".notes=$file_data" | jq ".secureNote.type=0" | bw encode | bw create item > /dev/null
       exit 0
-    fi
-    
-    if [[ "$item_folder_id" != "" ]]; then
-      if [[ "$item_folder_id" != "$folder_id" ]]; then
-        echo "Could not update secret found within a different folder"
-        exit 1
-      fi
     fi
 
     echo "Updating secret '$secret_name' ($id)"
